// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package productsqlc

import (
	"context"
)

type Querier interface {
	FindAll(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
