// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package productsqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	FindAll(ctx context.Context) ([]Product, error)
	Save(ctx context.Context, arg SaveParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
